properties:
  - name: DEFAULT_NAVIGATOR_DIRECTORY_KEY
    type: std::string
    static: true
    const: true
    init_with: "\"default_navigator_directory\""
  - name: config_filename
    type: std::string
    constructor_arg: true
    init_with: "\"/Users/markoates/Repos/me/config/hexagon.boot.cfg\""
  - name: config
    type: AllegroFlare::Config
    init_with: config_filename
functions:
  - name: initialize
    type: void
    body: config.load();
  - name: get_default_navigator_directory
    type: std::string
    body: |
      return config.get_or_default_str("", DEFAULT_NAVIGATOR_DIRECTORY_KEY, "/Users/markoates/Repos/hexagon");
dependencies:
  - symbol: AllegroFlare::Config
    headers: [ AllegroFlare/Config.hpp ]
