#!/bin/bash

yellow='\033[1;33m'
reset_text='\033[0m'

if [ "$#" == "0" ]
then
  echo "Error: You must provide an argument, which should be a name of a component."
  echo "Example: \"./rr ProgramRunner\""
else
  chruby 2.5.1
  rerun "./build && make obj/$1.o && make bin/tests/$1Test && bin/tests/$1Test && make bin/examples/$1Example && bin/examples/$1Example"
  rerun -c $rerun_command --pattern "{quintessence/Hexagon/FileNavigator/Stage.q.yml,examples/Hexagon/FileNavigator/StageExample.cpp}"
fi
