parent_classes:
  - class: ::Action
    scope: public
    init_with: "\"System::Action::OpenConfigFile\", ActionData()"
properties:
  - name: config
    type: Hexagon::System::Config*
    init_with: nullptr
functions:
  - name: execute
    type: bool
    body: |
      Hexagon::System::Action::AttemptToCraeteCodeEditorStageFromFilename action;
      return action.execute();
    body_dependency_symbols:
      - Hexagon::System::Action::AttemptToCraeteCodeEditorStageFromFilename
dependencies:
  - symbol: ::Action
    headers: [ Hexagon/Action.hpp ]
  - symbol: Hexagon::System::Config*
    headers: [ Hexagon/System/Config.hpp ]
  - symbol: Hexagon::System::Action::AttemptToCraeteCodeEditorStageFromFilename
    headers: [ Hexagon/System/Action/AttemptToCraeteCodeEditorStageFromFilename.hpp ]

